/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiStrategy: typeof import('./src/components/AiStrategy.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BaseScroller: typeof import('./src/components/base/BaseScroller.vue')['default']
    CoinSelector: typeof import('./src/components/trading/CoinSelector.vue')['default']
    CustomerService: typeof import('./src/components/CustomerService.vue')['default']
    FaqSection: typeof import('./src/components/FaqSection.vue')['default']
    FloatingServiceBtn: typeof import('./src/components/FloatingServiceBtn.vue')['default']
    MarketOverview: typeof import('./src/components/MarketOverview.vue')['default']
    MobileTabBar: typeof import('./src/components/MobileTabBar.vue')['default']
    OrderBook: typeof import('./src/components/trading/OrderBook.vue')['default']
    PriceTicker: typeof import('./src/components/PriceTicker.vue')['default']
    ResponsiveView: typeof import('./src/components/ResponsiveView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsBar: typeof import('./src/components/StatsBar.vue')['default']
    TradingChart: typeof import('./src/components/trading/TradingChart.vue')['default']
    TransactionList: typeof import('./src/components/trading/TransactionList.vue')['default']
    Transfer: typeof import('./src/components/Transfer.vue')['default']
    WalletConnect: typeof import('./src/components/WalletConnect.vue')['default']
  }
}
