/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AAvatarGroup: typeof import('ant-design-vue/es')['AvatarGroup']
    AiStrategy: typeof import('./components/AiStrategy.vue')['default']
    AiStrategyCard: typeof import('./components/home/AiStrategyCard.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppLoadingSpinner: typeof import('./components/base/AppLoadingSpinner.vue')['default']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ATable: typeof import('ant-design-vue/es')['Table']
    BaseScroller: typeof import('./components/base/BaseScroller.vue')['default']
    CoinSelector: typeof import('./components/trading/CoinSelector.vue')['default']
    CustomerService: typeof import('./components/CustomerService.vue')['default']
    FaqSection: typeof import('./components/FaqSection.vue')['default']
    FloatingServiceBtn: typeof import('./components/FloatingServiceBtn.vue')['default']
    FollowModal: typeof import('./components/follow/FollowModal.vue')['default']
    GAnimateButton: typeof import('./components/base/GAnimateButton.vue')['default']
    GIframe: typeof import('./components/base/GIframe.vue')['default']
    GLightweightChart: typeof import('./components/base/GLightweightChart.vue')['default']
    HomeAi: typeof import('./components/home/HomeAi.vue')['default']
    HomeBanner: typeof import('./components/home/HomeBanner.vue')['default']
    HomeBannerAd: typeof import('./components/home/HomeBannerAd.vue')['default']
    HomeBreakingNews: typeof import('./components/home/HomeBreakingNews.vue')['default']
    HomeCharity: typeof import('./components/home/HomeCharity.vue')['default']
    HomeCommonProblem: typeof import('./components/home/HomeCommonProblem.vue')['default']
    HomeIntroduce: typeof import('./components/home/HomeIntroduce.vue')['default']
    HomeNft: typeof import('./components/home/HomeNft.vue')['default']
    HomeNotice: typeof import('./components/home/HomeNotice.vue')['default']
    HomePortfolio: typeof import('./components/home/HomePortfolio.vue')['default']
    HomeQuotes: typeof import('./components/home/HomeQuotes.vue')['default']
    HomeSafeList: typeof import('./components/home/HomeSafeList.vue')['default']
    HomeTitleHeader: typeof import('./components/base/HomeTitleHeader.vue')['default']
    HomeTrendAnalysis: typeof import('./components/home/HomeTrendAnalysis.vue')['default']
    HomeWeb3: typeof import('./components/home/HomeWeb3.vue')['default']
    LanguageSelector: typeof import('./components/LanguageSelector.vue')['default']
    MarketOverview: typeof import('./components/MarketOverview.vue')['default']
    MobileTabBar: typeof import('./components/MobileTabBar.vue')['default']
    OrderBook: typeof import('./components/trading/OrderBook.vue')['default']
    PriceTicker: typeof import('./components/PriceTicker.vue')['default']
    ResponsiveView: typeof import('./components/ResponsiveView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsBar: typeof import('./components/StatsBar.vue')['default']
    TradeForm: typeof import('./components/trading/TradeForm.vue')['default']
    TradeOrders: typeof import('./components/trading/TradeOrders.vue')['default']
    TradingChart: typeof import('./components/trading/TradingChart.vue')['default']
    TransactionList: typeof import('./components/trading/TransactionList.vue')['default']
    Transfer: typeof import('./components/Transfer.vue')['default']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanProgress: typeof import('vant/es')['Progress']
    VanSlider: typeof import('vant/es')['Slider']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    WalletConnect: typeof import('./components/WalletConnect.vue')['default']
  }
}
