/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiStrategy: typeof import('./components/AiStrategy.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppLoadingSpinner: typeof import('./components/base/AppLoadingSpinner.vue')['default']
    BaseScroller: typeof import('./components/base/BaseScroller.vue')['default']
    CoinSelector: typeof import('./components/trading/CoinSelector.vue')['default']
    CustomerService: typeof import('./components/CustomerService.vue')['default']
    FaqSection: typeof import('./components/FaqSection.vue')['default']
    FloatingServiceBtn: typeof import('./components/FloatingServiceBtn.vue')['default']
    LanguageSelector: typeof import('./components/LanguageSelector.vue')['default']
    MarketOverview: typeof import('./components/MarketOverview.vue')['default']
    MobileTabBar: typeof import('./components/MobileTabBar.vue')['default']
    OrderBook: typeof import('./components/trading/OrderBook.vue')['default']
    PriceTicker: typeof import('./components/PriceTicker.vue')['default']
    ResponsiveView: typeof import('./components/ResponsiveView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsBar: typeof import('./components/StatsBar.vue')['default']
    TradingChart: typeof import('./components/trading/TradingChart.vue')['default']
    TransactionList: typeof import('./components/trading/TransactionList.vue')['default']
    Transfer: typeof import('./components/Transfer.vue')['default']
    WalletConnect: typeof import('./components/WalletConnect.vue')['default']
  }
}
